<h1><center> IMDB Dataset of 50K Movie Reviews

In [79]:
import pandas as pd
import numpy as np

In [80]:
pd.set_option('display.max_columns', 3)
pd.set_option('display.max_rows', 100)

In [81]:
data = pd.read_csv("IMDB Dataset.csv", encoding="utf-8")
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [82]:
data.columns

Index(['review', 'sentiment'], dtype='object')

In [83]:
data.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [85]:
data.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [86]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [87]:
# Gestion des valeurs dupliqées

data['review'].duplicated().sum()

418

In [88]:
# Supprimer les valeurs dupliquées
data.drop_duplicates(inplace= True)

print(data['review'].duplicated().sum())

0

In [89]:
data['sentiment'].value_counts()

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

In [90]:
data['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [91]:
import csv
#data.to_csv('IMDB_clean_Dataset_Visualization.csv', header= True, index= False, quoting=csv.QUOTE_ALL)
data.to_csv('IMDB_clean_Dataset.csv', header= True, index= False, encoding="utf-8")
print("Les données ont été enregistré avec succés!")

Les données ont été enregistré avec succés!

# Data Cleaning

In [92]:
data = pd.read_csv('IMDB_clean_Dataset.csv', encoding="utf-8")
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## 1)- Remove html code

In [93]:
import re

def remove_noisy_data(text):
    clean_text = re.sub(r'<[^>]*>', '' ,text)
    return clean_text



data['review'] = data['review'].apply(remove_noisy_data)

In [94]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## 2)- Remove spaces

In [95]:
def remove_spaces(text):
    text = text.strip()
    clean_text = re.sub(r'\s+', ' ', text)
    return clean_text


data['review'] = data['review'].apply(remove_spaces)

## 3)- Remove punctuation

In [96]:
import string

def remove_punctuation(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

data['review'] = data['review'].apply(remove_punctuation)

## 4)- Remove numbers

In [97]:
def remove_numbers(text):
    clean_text = re.sub('\d+', '', text)
    return clean_text

data['review'] = data['review'].apply(remove_numbers)

## 5)- Remove accents

In [98]:
import unicodedata
def remove_accents(text):
    text= unicodedata.normalize('NFD', text)
    text = "".join([c for c in text if unicodedata.category(c)!= 'Mn'])
    return text

data['review'] = data['review'].apply(remove_accents)

## 6)- Lower case

In [99]:
def lower_case(text):
    text_clean= text.lower()
    return text_clean

data['review'] = data['review'].apply(lower_case)

## 7)- Lemmatizing

In [100]:
from nltk.stem import WordNetLemmatizer

def stemming(text):
    lema = WordNetLemmatizer()
    text = ' '.join([lema.lemmatize(word) for word in text.split()])
    return text
data['review']=data['review'].apply(stemming)

## 8)- tokenization and remove stop words

In [101]:
import nltk

In [102]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def remove_english_stop_words(text):
    english_stops = set(stopwords.words('english'))
    tokens = word_tokenize(text)
    filtered_tokens = ' '.join([word for word in tokens if word not in english_stops])
    return filtered_tokens


data['review'] = data['review'].apply(remove_english_stop_words)

In [76]:
data.head(20)

                                               review sentiment
0   [one, reviewer, ha, mentioned, watching, oz, e...  positive
1   [wonderful, little, production, filming, techn...  positive
2   [thought, wa, wonderful, way, spend, time, hot...  positive
3   [basically, family, little, boy, jake, think, ...  negative
4   [petter, matteis, love, time, money, visually,...  positive
5   [probably, alltime, favorite, movie, story, se...  positive
6   [sure, would, like, see, resurrection, dated, ...  positive
7   [show, wa, amazing, fresh, innovative, idea, f...  negative
8   [encouraged, positive, comment, film, wa, look...  negative
9   [like, original, gut, wrenching, laughter, lik...  positive
10  [phil, alien, one, quirky, film, humour, based...  negative
11  [saw, movie, wa, came, recall, scariest, scene...  negative
12  [im, big, fan, boll, work, many, enjoyed, movi...  negative
13  [cast, played, shakespeareshakespeare, losti, ...  negative
14  [fantastic, movie, three, prisoner, become, fa...  positive
15  [kind, drawn, erotic, scene, realize, wa, one,...  negative
16  [film, simply, remade, one, bad, film, fails, ...  positive
17  [movie, made, one, top, awful, movie, horrible...  negative
18  [remember, filmit, wa, first, film, watched, c...  positive
19  [awful, film, must, real, stinker, nominated, ...  negative

In [77]:
data.to_csv('Final_clean_Dataset_nltk.csv', header= True, index= False, encoding="utf-8")