<h1><center> IMDB Dataset of 50K Movie Reviews

In [30]:
import pandas as pd
import numpy as np

In [36]:
pd.set_option('display.max_columns', 3)
pd.set_option('display.max_rows', 50)

In [3]:
data = pd.read_csv("IMDB Dataset.csv")
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [44]:
data.columns

Index(['review', 'sentiment'], dtype='object')

In [4]:
data.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [6]:
data.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [7]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [21]:
# Gestion des valeurs dupliqées

data['review'].duplicated().sum()

418

In [22]:
# Supprimer les valeurs dupliquées
data.drop_duplicates(inplace= True)

print(data['review'].duplicated().sum())

0

In [29]:
data['sentiment'].value_counts()

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

In [31]:
data['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [43]:
data.to_csv('IMDB_clean_Dataset.csv', header= True, index= False)
print("Les données ont été enregistré avec succés!")

Les données ont été enregistré avec succés!

## 1)- Remove noisy data (html code)

In [55]:
from bs4 import BeautifulSoup
import re

def remove_noisy_data(text):
    soup = BeautifulSoup(text, "html.parser")
    text = soup.get_text()
    text = re.sub('\[[^]]*\]', '', text)
    return text



data['review'] = data['review'].apply(remove_noisy_data)

c:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\bs4\__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(

In [84]:
text = "Hello good, great"
text = re.sub('good|great', '1', text)
text

'Hello 1, 1'